#!/bin/bash

# Secure single-file log backup
# - All logs concatenated into ONE text file with headers
# - File owned by root:root, permissions 600
# - Backup saved in /home/vagrant/hello

BACKUP_DIR="/home/vagrant/hello"
TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
BACKUP_FILE="all_logs_${TIMESTAMP}.txt"     # Single output file

mkdir -p "$BACKUP_DIR"

echo "Starting consolidated log backup at $(date)"
echo "Backup will be saved as: $BACKUP_DIR/$BACKUP_FILE"

# Temporary file for the consolidated log
TEMP_LOG=$(mktemp)

# Header for the backup
echo "===================================================" >> "$TEMP_LOG"
echo "     LINUX LOG BACKUP - $TIMESTAMP" >> "$TEMP_LOG"
echo "     Host: $(hostname)" >> "$TEMP_LOG"
echo "     Generated by: $(whoami) on $(date)" >> "$TEMP_LOG"
echo "===================================================" >> "$TEMP_LOG"
echo "" >> "$TEMP_LOG"

# Helper function to add a log file with header
add_log() {
    local title="$1"
    local path="$2"
    if [ -f "$path" ]; then
        echo ">>> $title ($path) - $(date)" >> "$TEMP_LOG"
        echo "---------------------------------------------------" >> "$TEMP_LOG"
        cat "$path" >> "$TEMP_LOG" 2>/dev/null || echo "[Error: Could not read $path]" >> "$TEMP_LOG"
        echo "" >> "$TEMP_LOG"
        echo ">>> END OF $title" >> "$TEMP_LOG"
        echo "" >> "$TEMP_LOG"
    fi
}

# Helper for directories (e.g., /var/log/apt)
add_dir_logs() {
    local dir_title="$1"
    local dir_path="$2"
    if [ -d "$dir_path" ]; then
        echo ">>> DIRECTORY: $dir_title ($dir_path) - $(date)" >> "$TEMP_LOG"
        echo "---------------------------------------------------" >> "$TEMP_LOG"
        find "$dir_path" -type f -name "*.log" -exec echo ">>> FILE: {}" \; -exec cat {} \; -exec echo "" \; >> "$TEMP_LOG" 2>/dev/null
        echo ">>> END OF $dir_title" >> "$TEMP_LOG"
        echo "" >> "$TEMP_LOG"
    fi
}

# Add main log files
add_log "kern.log"          /var/log/kern.log
add_log "syslog"            /var/log/syslog
add_log "auth.log"          /var/log/auth.log
add_log "dpkg.log"          /var/log/dpkg.log
add_log "cloud-init.log"    /var/log/cloud-init.log
add_log "cloud-init-output.log" /var/log/cloud-init-output.log
add_log "apport.log"        /var/log/apport.log
add_log "alternatives.log"  /var/log/alternatives.log
add_log "dmesg (current)"   /var/log/dmesg

# Add rotated dmesg files
for f in /var/log/dmesg.*; do
    [ -f "$f" ] && add_log "dmesg rotated: $(basename "$f")" "$f"
done

# Add apt history
add_dir_logs "APT logs" /var/log/apt

# Add journalctl output (last 7 days and current boot)
echo ">>> journalctl --since '7 days ago' - $(date)" >> "$TEMP_LOG"
journalctl --since "7 days ago" >> "$TEMP_LOG" 2>/dev/null || echo "[journalctl not available or error]" >> "$TEMP_LOG"
echo "" >> "$TEMP_LOG"
echo ">>> END OF journalctl (7 days)" >> "$TEMP_LOG"
echo "" >> "$TEMP_LOG"

echo ">>> journalctl (current boot)" >> "$TEMP_LOG"
journalctl -b >> "$TEMP_LOG" 2>/dev/null
echo ">>> END OF journalctl (current boot)" >> "$TEMP_LOG"

# Final footer
echo "===================================================" >> "$TEMP_LOG"
echo "               END OF BACKUP" >> "$TEMP_LOG"
echo "===================================================" >> "$TEMP_LOG"

# Move the consolidated file to backup location with secure permissions
install -m 600 "$TEMP_LOG" "$BACKUP_DIR/$BACKUP_FILE"
chown root:root "$BACKUP_DIR/$BACKUP_FILE"

# Clean up
rm -f "$TEMP_LOG"

echo "Consolidated backup completed!"
echo "Single file created: $BACKUP_DIR/$BACKUP_FILE"
echo "Size: $(du -h "$BACKUP_DIR/$BACKUP_FILE" | cut -f1)"
echo "Only root can read/write this file."
